spring.application.name=Brook-Auth

spring.docker.compose.enabled=false
Jwt.secret=5t/ISa+sdgqdNcG/cNOVtS6M6Viar+etwliOOes1ybc=\\n


spring.datasource.url=jdbc:postgresql://localhost:5432/brook
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create