spring.application.name=Brook-Auth

spring.docker.compose.enabled=false
Jwt.secret=5t/ISa+sdgqdNcG/cNOVtS6M6Viar+etwliOOes1ybc=\\n


spring.datasource.url=jdbc:postgresql://localhost:5432/brook
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create

#Kafka config
spring.kafka.producer.bootstrap-servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
spring.kafka.topic.name=testing_json
spring.kafka.producer.value-serializer=org.akal.Brook_Auth.Serializer.UserInfoSerializer